server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:mysql://127.0.0.1:3306/mo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:p6spy:mysql://127.0.0.1:3306/mo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
      db-config:
        # 主键类型
        id-type: auto
        table-prefix: "mo_"
  type-aliases-package: com.mouday.blogapi.pojo

config:
  jwt:
    # 加密密钥
    secret: 123456
    # token有效时长 单位:秒
    expire: 3600
    # header 名称
    token: "X-Token"
