
GET {{baseUrl}}/error

###
GET {{baseUrl}}/exceptionxx

###

GET {{baseUrl}}/users?page=1


###

GET {{baseUrl}}/users?page=1&keywords=李白


###
GET {{baseUrl}}/user?id=2
X-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwiZXhwIjoxNjA3OTE2NzQxLCJ1c2VybmFtZSI6IuadqOaVrOS5iyJ9.3Idb076ySqiN9-_xvCvVcDsZmaUnqgjSruiKdbkY0KI

###

DELETE {{baseUrl}}/user?id=92

###

GET {{baseUrl}}/users

###
GET {{baseUrl}}/blogs

###

GET {{baseUrl}}/blog?id=1
###

POST {{baseUrl}}/user
Content-Type: application/json

{"id": 67, "name":  "李大白", "dynastyId":  1}


###
GET {{baseUrl}}/dynasty

###

GET {{baseUrl}}/dynastyWithUserCount

###
POST {{baseUrl}}/blogStatus
Content-Type: application/json

{"id": 167, "isShow":  true}

###
POST {{baseUrl}}/userPassword
Content-Type: application/json

{"id": 16, "password":  "123456"}

###

POST {{baseUrl}}/login
Content-Type: application/json

{"username": "杨敬之", "password":  "123456"}

###

GET  {{baseUrl}}/roleList

###

POST {{baseUrl}}/role
Content-Type: application/json

{"name":  "超级管理员"}

###

GET {{baseUrl}}/userInfo
X-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwiZXhwIjoxNjA4MDg5MTQyLCJ1c2VybmFtZSI6IuadqOaVrOS5iyJ9._Ghh1HuaM1bPqVaRO6cbxPU7OT82QNpy_3YrrGKU20Y

###

GET {{baseUrl}}/roleListWithPermission

###
POST {{baseUrl}}/sendMail
Content-Type: application/json

{"toUser":  "1940607002@qq.com", "subject":  "邮件标题", "content":  "邮件内容"}

###

GET {{baseUrl}}/emailList

###
